#ifndef SOPSTORECLINET_GLOBAL_H
#define SOPSTORECLINET_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SOPSTORECLINET_LIBRARY)
#  define SOPSTORECLINETSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SOPSTORECLINETSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SOPSTORECLINET_GLOBAL_H
